import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ArrowLeft, Database, Search, ShieldCheck, Sparkles } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useQuery, useQueryClient } from "@tanstack/react-query";

const DEV_SESSION_KEY = "dev_unlocked";

interface AIExercise {
  id: string;
  name: string;
  muscle_group: string;
  sub_muscle: string;
  equipment: string;
  movement_pattern: string;
  is_unilateral: boolean;
  created_by: string | null;
}

export default function Developer() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [actionLoading, setActionLoading] = useState<string | null>(null);

  useEffect(() => {
    if (sessionStorage.getItem(DEV_SESSION_KEY) !== "true") {
      navigate("/profile", { replace: true });
    }
  }, [navigate]);

  const { data: pendingExercises, isLoading } = useQuery({
    queryKey: ["ai-exercises-pending"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("exercises")
        .select("id, name, muscle_group, sub_muscle, equipment, movement_pattern, is_unilateral, created_by")
        .eq("source", "ai_generated")
        .eq("is_approved", false);
      if (error) throw error;
      return data as AIExercise[];
    },
  });

  const handleApprove = async (id: string) => {
    setActionLoading(id);
    await supabase.from("exercises").update({ is_approved: true }).eq("id", id);
    queryClient.invalidateQueries({ queryKey: ["ai-exercises-pending"] });
    setActionLoading(null);
  };

  const handleRemove = async (id: string) => {
    setActionLoading(id);
    await supabase.from("exercises").delete().eq("id", id);
    queryClient.invalidateQueries({ queryKey: ["ai-exercises-pending"] });
    setActionLoading(null);
  };

  if (sessionStorage.getItem(DEV_SESSION_KEY) !== "true") return null;

  return (
    <div className="mx-auto max-w-lg px-5 pt-8 pb-28">
      <button
        onClick={() => navigate("/profile")}
        className="flex items-center gap-1.5 text-sm text-muted-foreground mb-6 hover:text-foreground transition-colors"
      >
        <ArrowLeft className="h-4 w-4" /> Profile
      </button>

      <h1 className="text-2xl font-semibold mb-1">Developer</h1>
      <p className="text-sm text-muted-foreground mb-8">Tools here are for testing only.</p>

      {/* Exercise API */}
      <Card className="rounded-2xl border-border p-5 mb-4">
        <div className="flex items-start gap-3">
          <Search className="h-5 w-5 text-muted-foreground mt-0.5 shrink-0" />
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1">
              <span className="font-medium text-sm">Exercise API</span>
              <Badge variant="outline" className="text-[10px] px-1.5 py-0 rounded-full text-muted-foreground">
                Experimental
              </Badge>
            </div>
            <p className="text-xs text-muted-foreground mb-3">Search external exercise database via RapidAPI</p>
            <Button
              size="sm"
              variant="outline"
              className="rounded-xl text-xs"
              onClick={() => navigate("/profile/developer/exercise-api")}
            >
              Open API Search
            </Button>
          </div>
        </div>
      </Card>

      {/* Data Tools */}
      <Card className="rounded-2xl border-border p-5 mb-4">
        <div className="flex items-start gap-3">
          <Database className="h-5 w-5 text-muted-foreground mt-0.5 shrink-0" />
          <div className="flex-1 min-w-0">
            <span className="font-medium text-sm">Data tools</span>
            <div className="flex flex-wrap gap-2 mt-3">
              <Button size="sm" variant="outline" className="rounded-xl text-xs" disabled>
                Clear my test data
              </Button>
              <Button size="sm" variant="outline" className="rounded-xl text-xs" disabled>
                Reseed exercises
              </Button>
            </div>
          </div>
        </div>
      </Card>

      {/* AI Exercise Review */}
      <Card className="rounded-2xl border-border p-5 mb-4">
        <div className="flex items-start gap-3">
          <Sparkles className="h-5 w-5 text-muted-foreground mt-0.5 shrink-0" />
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1">
              <span className="font-medium text-sm">AI Exercise Review</span>
              <Badge variant="outline" className="text-[10px] px-1.5 py-0 rounded-full text-muted-foreground">
                Governance
              </Badge>
            </div>
            <p className="text-xs text-muted-foreground mb-3">
              Exercises generated by AI — review before they enter the master list
            </p>

            {isLoading ? (
              <p className="text-xs text-muted-foreground">Loading…</p>
            ) : !pendingExercises?.length ? (
              <p className="text-xs text-muted-foreground/60">No exercises pending review</p>
            ) : (
              <div className="space-y-3">
                {pendingExercises.map((ex) => (
                  <div key={ex.id} className="border border-border rounded-xl p-3 space-y-1.5">
                    <p className="text-sm font-semibold">{ex.name}</p>
                    <p className="text-[11px] text-muted-foreground">
                      {ex.muscle_group} · {ex.sub_muscle} · {ex.equipment} · {ex.movement_pattern}
                    </p>
                    {ex.is_unilateral && (
                      <Badge variant="outline" className="text-[10px] px-1.5 py-0 rounded-full text-muted-foreground">
                        Unilateral
                      </Badge>
                    )}
                    {ex.created_by && (
                      <p className="text-[10px] text-muted-foreground/50 truncate">
                        Created by: {ex.created_by}
                      </p>
                    )}
                    <div className="flex gap-2 pt-1">
                      <Button
                        size="sm"
                        variant="outline"
                        className="rounded-xl text-xs border-green-300 text-green-700 hover:bg-green-50"
                        disabled={actionLoading === ex.id}
                        onClick={() => handleApprove(ex.id)}
                      >
                        Approve
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        className="rounded-xl text-xs border-red-300 text-red-700 hover:bg-red-50"
                        disabled={actionLoading === ex.id}
                        onClick={() => handleRemove(ex.id)}
                      >
                        Remove
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </Card>

      {/* System Status */}
      <Card className="rounded-2xl border-border p-5">
        <div className="flex items-start gap-3">
          <ShieldCheck className="h-5 w-5 text-muted-foreground mt-0.5 shrink-0" />
          <div className="flex-1 min-w-0">
            <span className="font-medium text-sm">System Status</span>
            <div className="mt-3 space-y-2">
              <div className="flex items-center justify-between">
                <p className="text-xs text-muted-foreground">exercise-search-external</p>
                <Badge variant="outline" className="text-[10px] px-1.5 py-0 rounded-full text-muted-foreground">
                  v1.0.1
                </Badge>
              </div>
              <div className="text-[11px] text-muted-foreground/70 space-y-0.5">
                <p>• Fixed incorrect RapidAPI query parameter (search instead of name)</p>
                <p>• Added secure RapidAPI proxy via Edge Function</p>
                <p>• Removed client-side API key handling</p>
              </div>
            </div>
          </div>
        </div>
      </Card>
    </div>
  );
}
